### ISSUE TITLE
XMLHttpRequest error on CreatePaymentIntent

### ISSUE THREAD

**Issue by andreagr** [ezet/stripe-sdk#133]
On Flutter web 2.0.0 I get this error while trying to pay with the test **4000 0027 6000 3184**

I get this error:

```
ERROR_CreatePaymentIntentAndSubmit: XMLHttpRequest error.
TypeError: Cannot read property 'Symbol(dartx._get)' of null
    at buy (http://localhost:64441/packages/webOrder/mixins/payments.dart.lib.js:217:57)
    at buy.next (<anonymous>)
    at http://localhost:64441/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:64441/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:64441/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:64441/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:64441/dart_sdk.js:34473:17)
    at _Future.new.[_completeError] (http://localhost:64441/dart_sdk.js:34323:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64441/dart_sdk.js:34362:31)
    at Object._microtaskLoop (http://localhost:64441/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:64441/dart_sdk.js:39182:13)
    at http://localhost:64441/dart_sdk.js:34689:9
```

**Comment by ezet** [comment]
I don't think this is related to this library. Please comment if you think it is.
